chore: upgrade vitepress dependency to latest release candidate version
six-group/six-webcomponents pull request #124
Opened 2023-10-26 15:06 UTC by colinscz

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `main` branch for v2.x (or to a previous version branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2024-05-09 08:39 UTC, aggieN submitted a review, later dismissed

2024-06-21 08:26 UTC, ibirrer requested changes

2024-06-21 08:26 UTC, ibirrer commented on docs/.vitepress/theme/index.ts
> +const modules = import.meta.glob("../../examples/**/*.vue'", { eager: true });
```suggestion
const modules = import.meta.glob('../../examples/**/*.vue', { eager: true });
```

2024-06-21 08:42 UTC, ibirrer requested changes

2024-06-21 08:42 UTC, ibirrer commented on docs/.vitepress/theme/style.css
Borders should probably have the same color as the content:
![image](https://github.com/six-group/six-webcomponents/assets/1475511/c1640661-699a-4427-8add-59ba1e62d17c)

2024-06-21 08:42 UTC, ibirrer commented on docs/.vitepress/theme/style.css
> +  /*  --vp-button-brand-border: var(--vp-c-brand-2);*/
better remove than comment

2024-06-21 08:42 UTC, ibirrer commented on docs/.vitepress/theme/index.ts
> +  console.log(path);
remiove console.log

2024-06-21 08:42 UTC, ibirrer approved these changes

2024-06-21 08:44 UTC, ibirrer approved these changes

2024-06-21 08:44 UTC, ibirrer commented on docs/.vitepress/theme/style.css
Search seems broken:
![image](https://github.com/six-group/six-webcomponents/assets/1475511/2bc0e6d1-6529-4607-9106-2787d05690fe)

2024-06-21 14:39 UTC, colinscz commented on docs/.vitepress/theme/style.css
> +  /*  --vp-button-brand-border: var(--vp-c-brand-2);*/
936ea8ccb912e8cc1c0db2ad666f6cab49b1342c

2024-06-21 14:39 UTC, colinscz commented on docs/.vitepress/theme/index.ts
> +  console.log(path);
936ea8ccb912e8cc1c0db2ad666f6cab49b1342c

2024-07-26 08:45 UTC, colinscz commented on docs/.vitepress/theme/style.css
749bcb979c6092d94b1de5771071247ff98cf60e

2024-07-26 08:46 UTC, colinscz commented on docs/.vitepress/theme/style.css
749bcb979c6092d94b1de5771071247ff98cf60e

2024-07-31 08:48 UTC, pennal approved these changes

2024-07-31 08:50 UTC, merged