#236 Feature/add invalid attribute to file upload
six-group/six-webcomponents pull request #250
Opened 2024-04-25 15:18 UTC by franckdervaux

### 🔗 Linked issue
Resolves #236.

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Adds `invalid` and `error-text` properties to the `six-file-upload` component.  
It allows it to display error messages when it is invalid, for example if the selected file is too large.  
It also supports an `error-text` slot for displaying more complex error messages.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] I have updated the documentation accordingly.
- [x] All tests are passing
- [x] New/updated tests are included
- [x] I have updated the "upcoming" section inside _docs/changelog.md_ explaining the changes I contributed

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2024-04-26 06:00 UTC, davidemarcoli requested changes

2024-04-26 08:13 UTC, davidemarcoli approved these changes

2024-05-22 13:54 UTC, stefanrufer commented
@franckdervaux - as soon as you update the changelog according to the comment we will merge the PR.

2024-05-28 07:55 UTC, franckdervaux commented
@stefanrufer commit https://github.com/six-group/six-webcomponents/pull/250/commits/0a5ec9a3255d7a8fd9bd21c6b8069c0b716c8ebf has the proper change I believe?

2024-05-28 08:35 UTC, davidemarcoli commented
@stefanrufer @franckdervaux I've fixed the merge conflicts. I think it's ready now! Someone else has to approve it..

2024-05-29 14:37 UTC, stefanrufer approved these changes

2024-05-29 14:59 UTC, merged