Documentation with VitePress
six-group/six-webcomponents pull request #77
Opened 2023-08-10 14:09 UTC by ibirrer

2023-08-14 13:58 UTC, stefanrufer commented on docs/guide/angular.md
> +(TODO) for available events.
Fix TODO

2023-08-14 14:00 UTC, stefanrufer requested changes
two/three comments in the guide part.

2023-08-17 20:06 UTC, ibirrer commented on docs/guide/angular.md
> +(TODO) for available events.
Done

2023-08-18 09:34 UTC, colinscz commented on docs/guide/upgrade-v4.md
> +offers extensive capabilities.
I think there is no harm in mentioning the name of that library that exist internally. One thing that would be crucial to have is an easy way of finding that documentation and how to integrate this internal library. 

Maybe we can reference it in the internal teams channel or on our internal confluence. That way we can just say something like "find more information about this on our internal confluence space for the six webcomponents". 

@Riatomerehentroweard any suggestions from your side?

2023-08-18 09:50 UTC, stefanrufer approved these changes

2023-08-18 09:52 UTC, merged